#!/bin/bash


copy_to_repo_home () {
	cd home
	for filename in $(find . -type f | cut -c 3-); do
		cp -rv "$HOME/$filename" "$filename"
	done
	cd ..
}

copy_from_repo_home () {
	cd home
	for filename in $(find . -type f | cut -c 3-); do
		mkdir -p "$(dirname "$HOME/filename")" && cp -rv "$filename" "$HOME/$filename"
	done
	cd ..
}


# Check that $DOTS_BRANCH is properly defined
./check_dots_branch

if [ $? -ne 0 ]; then
	exit $?
fi

cd `dirname $0`

git switch common
git pull

case "$1" in
	"-in")
		copy_from_repo_home
		git switch "$DOTS_BRANCH"
		git pull
		copy_from_repo_home
		;;
	"-out")
		copy_to_repo_home
		git add .
		git commit -m "updating common"
		git push
		git switch "$DOTS_BRANCH"
		git pull
		copy_to_repo_home
		git add .
		git commit -m "updating $DOTS_BRANCH"
		git push
esac
git switch common
