#!/bin/bash

# Check that $DOTS_BRANCH is properly defined
./check_dots_branch

if [ $? -ne 0 ]; then
	exit $?
fi

cd `dirname $0`

case "$1" in
	"-in")
		git switch common
		rsync -r home ~/
		git switch "$DOTS_BRANCH"
		rsync -r home ~/
	"-out")
		git switch common
		rsync --existing -r ~/ home
		git switch "$DOTS_BRANCH"
		rsync --existing -r ~/ home
esac

git switch common



