#!/bin/bash

./check_dots_branch

if [ $? -ne 0 ]; then
	exit $?
fi

cd `dirname $0`

git switch common
git add home
git commit -m "updating common"
git push
if [ $? -ne 0 ]; then
	>&2 echo 'error: pushing to common failed'
	exit $?
fi
git switch "$DOTS_BRANCH"
git add home
git commit -m "updating $DOTS_BRANCH"
git push
if [ $? -ne 0 ]; then
	>&2 echo "error: pushing to $DOTS_BRANCH failed"
	exit $?
fi
git switch common
