#!/bin/sh

export DISPLAY=$(cat "$TURNSTILE_ENV_DIR/DISPLAY")
XTTY=$(cat "$TURNSTILE_ENV_DIR/XTTY")
[ -z "$DISPLAY" ] && exit 1

terminate() {
    xset -dpms
    SVDIR=".." sv down lockscreen
    kill -TERM "-$PGID"
}

ssh_active() {
    who | awk '{print $5}' | grep -v tmux
}

PGID=$(ps -o pgid= "$$")
trap terminate HUP INT TERM
xset +dpms dpms 5 5 5
{ slock; terminate; } &
{ while true; do sleep 180 && [ "$(cat /sys/devices/virtual/tty/tty0/active)" = "$XTTY" ] && [ -z "$(ssh_active)" ] && sudo /usr/bin/zzz > /dev/null; done } &
{ while true; do sleep 10 && xset +dpms dpms 5 5 5; done } &
exec pause
